version: '3'

services:
  create_certs:
    image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION}
    container_name: create_certs
    command: >
      bash -c '
        yum install -y -q -e 0 unzip;
        if [[ ! -f /certs/bundle.zip ]]; then
          bin/elasticsearch-certutil cert --silent --pem --in config/certificates/instances.yml -out /certs/bundle.zip;
          unzip /certs/bundle.zip -d /certs;
        fi;
        chown -R 1000:0 /certs
      '
    working_dir: /usr/share/elasticsearch
    env_file:
      - ./.env
    volumes:
      - /$ELASTIC_STACK_NAME/$CERTS_VOLUME_NAME:/certs:z
      - .:/usr/share/elasticsearch/config/certificates:z
    networks:
      - elastic
    deploy:
      placement:
        constraints:
          - "node.hostname==${MASTER_NODE_HOSTNAME}"

volumes:
  certs:
    driver: local

networks:
  elastic:
    driver: overlay
